baseURL = "https://apps.igormihalik.com/pracujucemamy.sk/"
defaultContentLanguage = "sk"
languageCode = "sk-sk"
title = "Pracujuce Mamy"

[menu]
[[menu.main]]
  url="https://pracujucemamy.darujme.sk/podporte-pracujuce-mamy-a927b/"
  title = "Podporte n√°s"
  weight = 5
[menu.main.params]
  target = '_blank'

[languages]
  [languages.sk]
    title = "Pracujuce Mamy"
    weight = 1
  [languages.en]
    title = "Working Moms"
    weight = 2

